package analytic.ofofo.net.apis.gmail.model;

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class reply_to extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"reply_to\",\"fields\":[{\"name\":\"real_name\",\"type\":[\"null\",\"string\"],\"doc\":\"\"},{\"name\":\"address\",\"type\":[\"null\",\"string\"],\"doc\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /**  */
  @Deprecated public java.lang.CharSequence real_name;
  /**  */
  @Deprecated public java.lang.CharSequence address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public reply_to() {}

  /**
   * All-args constructor.
   */
  public reply_to(java.lang.CharSequence real_name, java.lang.CharSequence address) {
    this.real_name = real_name;
    this.address = address;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return real_name;
    case 1: return address;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: real_name = (java.lang.CharSequence)value$; break;
    case 1: address = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'real_name' field.
   *    */
  public java.lang.CharSequence getRealName() {
    return real_name;
  }

  /**
   * Sets the value of the 'real_name' field.
   *    * @param value the value to set.
   */
  public void setRealName(java.lang.CharSequence value) {
    this.real_name = value;
  }

  /**
   * Gets the value of the 'address' field.
   *    */
  public java.lang.CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   *    * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /** Creates a new reply_to RecordBuilder */
  public static reply_to.Builder newBuilder() {
    return new reply_to.Builder();
  }
  
  /** Creates a new reply_to RecordBuilder by copying an existing Builder */
  public static reply_to.Builder newBuilder(reply_to.Builder other) {
    return new reply_to.Builder(other);
  }
  
  /** Creates a new reply_to RecordBuilder by copying an existing reply_to instance */
  public static reply_to.Builder newBuilder(reply_to other) {
    return new reply_to.Builder(other);
  }
  
  /**
   * RecordBuilder for reply_to instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<reply_to>
    implements org.apache.avro.data.RecordBuilder<reply_to> {

    private java.lang.CharSequence real_name;
    private java.lang.CharSequence address;

    /** Creates a new Builder */
    private Builder() {
      super(reply_to.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(reply_to.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.real_name)) {
        this.real_name = data().deepCopy(fields()[0].schema(), other.real_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.address)) {
        this.address = data().deepCopy(fields()[1].schema(), other.address);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing reply_to instance */
    private Builder(reply_to other) {
            super(reply_to.SCHEMA$);
      if (isValidValue(fields()[0], other.real_name)) {
        this.real_name = data().deepCopy(fields()[0].schema(), other.real_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.address)) {
        this.address = data().deepCopy(fields()[1].schema(), other.address);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'real_name' field */
    public java.lang.CharSequence getRealName() {
      return real_name;
    }
    
    /** Sets the value of the 'real_name' field */
    public reply_to.Builder setRealName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.real_name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'real_name' field has been set */
    public boolean hasRealName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'real_name' field */
    public reply_to.Builder clearRealName() {
      real_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'address' field */
    public java.lang.CharSequence getAddress() {
      return address;
    }
    
    /** Sets the value of the 'address' field */
    public reply_to.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.address = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'address' field has been set */
    public boolean hasAddress() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'address' field */
    public reply_to.Builder clearAddress() {
      address = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    public reply_to build() {
      try {
        reply_to record = new reply_to();
        record.real_name = fieldSetFlags()[0] ? this.real_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.address = fieldSetFlags()[1] ? this.address : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
